<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'tenants.view' => 'View tenants',
            'tenants.manage' => 'Manage tenants',
            'organizations.view' => 'View organizations',
            'organizations.manage' => 'Manage organizations',
            'branches.view' => 'View branches',
            'branches.manage' => 'Manage branches',
            'users.view' => 'View users',
            'users.manage' => 'Manage users',
            'roles.manage' => 'Manage roles',
            'audit.view' => 'View audit logs',
            'patients.view' => 'View patients',
            'patients.manage' => 'Manage patients',
            'patients.records.view' => 'View patient health records',
            'patients.records.manage' => 'Manage patient health records',
            'patients.documents.view' => 'View patient documents',
            'patients.documents.manage' => 'Manage patient documents',
            'clinics.view' => 'View clinics',
            'clinics.manage' => 'Manage clinics',
            'providers.view' => 'View providers',
            'providers.manage' => 'Manage providers',
            'specialties.view' => 'View specialties',
            'specialties.manage' => 'Manage specialties',
            'services.view' => 'View services',
            'services.manage' => 'Manage services',
            'schedules.view' => 'View schedules',
            'schedules.manage' => 'Manage schedules',
            'appointments.view' => 'View appointments',
            'appointments.manage' => 'Manage appointments',
            'appointments.queue.manage' => 'Manage appointment queue and check-in',
            'clinical.assessments.view' => 'View clinical assessments',
            'clinical.assessments.manage' => 'Manage clinical assessments',
            'clinical.notes.view' => 'View clinical SOAP notes',
            'clinical.notes.manage' => 'Manage clinical SOAP notes',
            'clinical.treatment.view' => 'View clinical treatment plans and sessions',
            'clinical.treatment.manage' => 'Manage clinical treatment plans and sessions',
            'clinical.progress.view' => 'View clinical progress notes',
            'clinical.progress.manage' => 'Manage clinical progress notes',
            'clinical.discharge.view' => 'View clinical discharge summaries',
            'clinical.discharge.manage' => 'Manage clinical discharge summaries',
            'clinical.exercises.view' => 'View exercise library and patient exercise plans',
            'clinical.exercises.manage' => 'Manage exercise library and patient exercise plans',
            'billing.invoices.view' => 'View billing invoices and tax rates',
            'billing.invoices.manage' => 'Manage billing invoices and tax rates',
            'billing.payments.view' => 'View payments and receipts',
            'billing.payments.manage' => 'Record and manage payments',
            'billing.packages.view' => 'View treatment packages',
            'billing.packages.manage' => 'Manage treatment packages and session consumption',
            'billing.refunds.manage' => 'Process billing refunds',
            'ai.view' => 'View AI agents, usage, audit, prompts, and models',
            'ai.manage' => 'Manage AI prompts and configuration',
            'ai.run' => 'Run AI agents',
            'tenant.ai.manage' => 'Manage tenant AI model routing settings',
            'health_guide.view' => 'View Health Guide conversations and safety rules',
            'health_guide.run' => 'Start and run Health Guide conversations and assisted booking',
            'whatsapp.view' => 'View WhatsApp accounts, conversations, and handoffs',
            'whatsapp.manage' => 'Manage WhatsApp accounts, reply to conversations, and handoffs',
            'reports.view' => 'View report AI analyses',
            'reports.analyze' => 'Start and regenerate report AI analyses',
            'reports.review' => 'Approve or reject report AI analyses',
            'medications.view' => 'View patient medications, schedules, and logs',
            'medications.manage' => 'Manage patient medications and schedules',
            'wellness.view' => 'View wellness content and recommendations',
            'wellness.manage' => 'Manage wellness content and patient preferences',
            'seo.view' => 'View SEO content entities and FAQs',
            'seo.manage' => 'Manage and publish SEO content entities and FAQs',
            'marketing.view' => 'View marketing attribution, referrals, segments, and email workflows',
            'marketing.manage' => 'Manage marketing attribution, referrals, segments, and email workflows',
            'crm.manage' => 'Manage marketing CRM leads',
            'experiments.manage' => 'Manage A/B experiments and variants',
            'templates.view' => 'View dynamic content templates',
            'templates.manage' => 'Manage dynamic content templates',
            'forms.view' => 'View dynamic form definitions',
            'forms.manage' => 'Manage dynamic forms and submissions',
            'workflows.view' => 'View automation workflows and runs',
            'workflows.manage' => 'Manage automation workflows',
            'languages.view' => 'View platform languages',
            'languages.manage' => 'Manage platform languages and scopes',
            'tenant.languages.manage' => 'Manage tenant language subset settings',
        ];

        foreach ($permissions as $slug => $name) {
            Permission::query()->updateOrCreate(
                ['slug' => $slug],
                ['name' => $name],
            );
        }

        $allPermissionIds = Permission::query()->pluck('id');

        $superAdmin = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'super_admin'],
            ['tenant_id' => null, 'name' => 'Super Admin'],
        );
        $superAdmin->permissions()->sync($allPermissionIds);

        $organizationAdmin = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'organization_admin'],
            ['tenant_id' => null, 'name' => 'Organization Admin'],
        );
        $organizationAdmin->permissions()->sync(
            Permission::query()->whereIn('slug', [
                'organizations.view',
                'organizations.manage',
                'branches.view',
                'branches.manage',
                'users.view',
                'users.manage',
                'roles.manage',
                'audit.view',
                'patients.view',
                'patients.manage',
                'patients.records.view',
                'patients.records.manage',
                'patients.documents.view',
                'patients.documents.manage',
                'clinics.view',
                'clinics.manage',
                'providers.view',
                'providers.manage',
                'specialties.view',
                'specialties.manage',
                'services.view',
                'services.manage',
                'schedules.view',
                'schedules.manage',
                'appointments.view',
                'appointments.manage',
                'appointments.queue.manage',
                'clinical.assessments.view',
                'clinical.assessments.manage',
                'clinical.notes.view',
                'clinical.notes.manage',
                'clinical.treatment.view',
                'clinical.treatment.manage',
                'clinical.progress.view',
                'clinical.progress.manage',
                'clinical.discharge.view',
                'clinical.discharge.manage',
                'clinical.exercises.view',
                'clinical.exercises.manage',
                'templates.view',
                'templates.manage',
                'forms.view',
                'forms.manage',
                'workflows.view',
                'workflows.manage',
                'billing.invoices.view',
                'billing.invoices.manage',
                'billing.payments.view',
                'billing.payments.manage',
                'billing.packages.view',
                'billing.packages.manage',
                'billing.refunds.manage',
                'ai.view',
                'ai.run',
                'tenant.ai.manage',
                'health_guide.view',
                'health_guide.run',
                'whatsapp.view',
                'whatsapp.manage',
                'reports.view',
                'reports.analyze',
                'reports.review',
                'medications.view',
                'medications.manage',
                'wellness.view',
                'wellness.manage',
                'seo.view',
                'seo.manage',
                'marketing.view',
                'marketing.manage',
                'crm.manage',
                'experiments.manage',
                'languages.view',
                'tenant.languages.manage',
            ])->pluck('id')
        );

        $branchManager = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'branch_manager'],
            ['tenant_id' => null, 'name' => 'Branch Manager'],
        );
        $branchManager->permissions()->sync(
            Permission::query()->whereIn('slug', [
                'organizations.view',
                'branches.view',
                'branches.manage',
                'users.view',
                'audit.view',
                'patients.view',
                'patients.manage',
                'patients.records.view',
                'patients.records.manage',
                'patients.documents.view',
                'patients.documents.manage',
                'clinics.view',
                'specialties.view',
                'providers.view',
                'providers.manage',
                'services.view',
                'services.manage',
                'schedules.view',
                'schedules.manage',
                'appointments.view',
                'appointments.manage',
                'appointments.queue.manage',
                'clinical.assessments.view',
                'clinical.assessments.manage',
                'clinical.notes.view',
                'clinical.notes.manage',
                'clinical.treatment.view',
                'clinical.treatment.manage',
                'clinical.progress.view',
                'clinical.progress.manage',
                'clinical.discharge.view',
                'clinical.discharge.manage',
                'clinical.exercises.view',
                'clinical.exercises.manage',
                'billing.invoices.view',
                'billing.invoices.manage',
                'billing.payments.view',
                'billing.payments.manage',
                'billing.packages.view',
                'billing.packages.manage',
                'billing.refunds.manage',
                'ai.view',
                'ai.run',
                'health_guide.view',
                'health_guide.run',
                'whatsapp.view',
                'whatsapp.manage',
                'reports.view',
                'reports.analyze',
                'reports.review',
                'medications.view',
                'medications.manage',
                'wellness.view',
                'wellness.manage',
                'seo.view',
                'seo.manage',
                'marketing.view',
                'marketing.manage',
                'crm.manage',
                'experiments.manage',
            ])->pluck('id')
        );

        // Self-serve personas for OTP / signup onboarding.
        $patient = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'patient'],
            ['name' => 'Patient', 'tenant_id' => null],
        );
        $patient->permissions()->sync(
            Permission::query()->whereIn('slug', [
                'health_guide.view',
                'health_guide.run',
                'wellness.view',
                'medications.view',
                'medications.manage',
            ])->pluck('id')
        );

        $provider = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'provider'],
            ['name' => 'Doctor / Provider', 'tenant_id' => null],
        );
        $provider->permissions()->sync(
            Permission::query()->whereIn('slug', [
                'patients.view',
                'patients.records.view',
                'patients.documents.view',
                'appointments.view',
                'appointments.manage',
                'appointments.queue.manage',
                'providers.view',
                'schedules.view',
                'clinical.assessments.view',
                'clinical.notes.view',
                'clinical.treatment.view',
                'clinical.progress.view',
                'clinical.discharge.view',
                'clinical.exercises.view',
                'health_guide.view',
                'health_guide.run',
                'ai.view',
                'ai.run',
                'reports.view',
                'medications.view',
            ])->pluck('id')
        );

        $clinicAdmin = Role::query()->updateOrCreate(
            ['tenant_key' => 'system', 'slug' => 'clinic_admin'],
            ['name' => 'Clinic', 'tenant_id' => null],
        );
        $clinicAdmin->permissions()->sync(
            Permission::query()->whereIn('slug', [
                'organizations.view',
                'organizations.manage',
                'branches.view',
                'patients.view',
                'patients.manage',
                'patients.records.view',
                'patients.records.manage',
                'patients.documents.view',
                'patients.documents.manage',
                'clinics.view',
                'clinics.manage',
                'providers.view',
                'providers.manage',
                'specialties.view',
                'services.view',
                'services.manage',
                'schedules.view',
                'schedules.manage',
                'appointments.view',
                'appointments.manage',
                'appointments.queue.manage',
                'clinical.assessments.view',
                'clinical.assessments.manage',
                'clinical.notes.view',
                'clinical.notes.manage',
                'clinical.treatment.view',
                'clinical.treatment.manage',
                'billing.invoices.view',
                'billing.payments.view',
                'billing.packages.view',
                'ai.view',
                'health_guide.view',
                'reports.view',
                'reports.analyze',
                'medications.view',
                'wellness.view',
            ])->pluck('id')
        );
    }
}
